<?php

function iris_entity_createEntity($entityType, $entityPropertiesArray, $credentials){
  
   $data = array(
    'credentials' => json_encode($credentials),
    );
  
  foreach($entityPropertiesArray as $key => $value){
  
    $data[$key] = json_encode($value);
    
  }
  
  $options = array(
    'method' => 'POST',
    'data' => drupal_http_build_query($data),
    'timeout' => 15,
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
  );
  
  $result = drupal_http_request(variable_get("iris_server_address") . "/entity/create/".$entityType, $options);
      
}